package ru.cyberbiology;

import java.awt.Frame;
import ru.cyberbiology.util.ProjectProperties;

/**
 *
 * @author Sergey Sokolov <xlamserg@gmail.com>
 */
public class SettingsDialog extends javax.swing.JDialog {

    private final ProjectProperties properties;

    public SettingsDialog(Frame parent, boolean modal) {
        super(parent, modal);
        properties = ProjectProperties.getInstance();
        initComponents();
        cbMultiCell.setSelected(properties.getBoolean("EnableMultiCell"));
        cbRelativeByEnergy.setSelected(properties.getBoolean("EnableRelativeByEnergy"));
        cbRelativeByMinerals.setSelected(properties.getBoolean("EnableRelativeByMinerals"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panelSettingsGeneral = new javax.swing.JPanel();
        panelSettingaBots = new javax.swing.JPanel();
        cbMultiCell = new javax.swing.JCheckBox();
        cbRelativeByEnergy = new javax.swing.JCheckBox();
        cbRelativeByMinerals = new javax.swing.JCheckBox();
        buttonPanel = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Параметры");

        javax.swing.GroupLayout panelSettingsGeneralLayout = new javax.swing.GroupLayout(panelSettingsGeneral);
        panelSettingsGeneral.setLayout(panelSettingsGeneralLayout);
        panelSettingsGeneralLayout.setHorizontalGroup(
            panelSettingsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        panelSettingsGeneralLayout.setVerticalGroup(
            panelSettingsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Общие", panelSettingsGeneral);

        cbMultiCell.setText("многоклеточность");

        cbRelativeByEnergy.setText("родство по энергии");

        cbRelativeByMinerals.setText("родство по минералам");
        cbRelativeByMinerals.setToolTipText("");

        javax.swing.GroupLayout panelSettingaBotsLayout = new javax.swing.GroupLayout(panelSettingaBots);
        panelSettingaBots.setLayout(panelSettingaBotsLayout);
        panelSettingaBotsLayout.setHorizontalGroup(
            panelSettingaBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingaBotsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSettingaBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMultiCell)
                    .addComponent(cbRelativeByEnergy)
                    .addComponent(cbRelativeByMinerals))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelSettingaBotsLayout.setVerticalGroup(
            panelSettingaBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingaBotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbMultiCell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRelativeByEnergy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRelativeByMinerals)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Боты", panelSettingaBots);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonOk.setText("ОК");
        buttonPanel.add(buttonOk);

        buttonCancel.setText("Отмена");
        buttonPanel.add(buttonCancel);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
        getContentPane().add(filler1, java.awt.BorderLayout.NORTH);
        getContentPane().add(filler2, java.awt.BorderLayout.WEST);
        getContentPane().add(filler3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox cbMultiCell;
    private javax.swing.JCheckBox cbRelativeByEnergy;
    private javax.swing.JCheckBox cbRelativeByMinerals;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel panelSettingaBots;
    private javax.swing.JPanel panelSettingsGeneral;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    void showSettingsDialog() {
        setVisible(true);
    }
}
