package ru.cyberbiology.ui;

import java.awt.Frame;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JCheckBox;
import ru.cyberbiology.util.ProjectProperties;

/**
 * Диалог параметров приложения.
 * 
 * @author Sergey Sokolov (xlamserg@gmail.com)
 */
public class SettingsDialog extends javax.swing.JDialog {

    private final ProjectProperties properties;
    private final Map<String, String> changedSettings = new HashMap();

    /**
     * Создает окно диалога параметров и загружает в него текущие значения параметров.
     * @param parent окно приложения, для которого вызывается диалог параметров
     * @param modal флаг модальности (взаимодействие с окном приложения невозможно пока
     *      не будет закрыт диалог параметров)
     */
    public SettingsDialog(Frame parent, boolean modal) {
        super(parent, modal);
        properties = ProjectProperties.getInstance();
        initComponents();
        loadSettings();
    }

    private void loadSettings() {
        cbMultiCell.setSelected(properties.getBoolean("EnableMultiCell"));
        cbRelativeByEnergy.setSelected(properties.getBoolean("EnableRelativeByEnergy"));
        cbRelativeByMinerals.setSelected(properties.getBoolean("EnableRelativeByMinerals"));
    }
    
    //CHECKSTYLE:OFF

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMineralsAccumulation = new javax.swing.ButtonGroup();
        tabbedPane = new javax.swing.JTabbedPane();
        panelSettingsGeneral = new javax.swing.JPanel();
        labelDevNote = new javax.swing.JLabel();
        panelSettingsWorld = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbMineralsAccClassic = new javax.swing.JRadioButton();
        rbMineralsAccHeight = new javax.swing.JRadioButton();
        panelSettingaBots = new javax.swing.JPanel();
        cbMultiCell = new javax.swing.JCheckBox();
        cbRelativeByEnergy = new javax.swing.JCheckBox();
        cbRelativeByMinerals = new javax.swing.JCheckBox();
        buttonPanel = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Параметры");

        labelDevNote.setText("Здесь будут общие настройки");

        javax.swing.GroupLayout panelSettingsGeneralLayout = new javax.swing.GroupLayout(panelSettingsGeneral);
        panelSettingsGeneral.setLayout(panelSettingsGeneralLayout);
        panelSettingsGeneralLayout.setHorizontalGroup(
            panelSettingsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDevNote)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        panelSettingsGeneralLayout.setVerticalGroup(
            panelSettingsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDevNote)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Общие", panelSettingsGeneral);

        jLabel1.setText("Накопление минералов:");

        bgMineralsAccumulation.add(rbMineralsAccClassic);
        rbMineralsAccClassic.setSelected(properties.getProperty("MineralsAccumulation", "").equals("classic"));
        rbMineralsAccClassic.setText("классическое");
        rbMineralsAccClassic.setToolTipText("Минералы накапливаются только в нижней половине мира с постоянной скоростью 1 минерал в пересчет");
        rbMineralsAccClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMineralsAccClassicActionPerformed(evt);
            }
        });

        bgMineralsAccumulation.add(rbMineralsAccHeight);
        rbMineralsAccHeight.setSelected(properties.getProperty("MineralsAccumulation", "").equals("height"));
        rbMineralsAccHeight.setText("по всей глубине");
        rbMineralsAccHeight.setToolTipText("Минералы накапливаются по всей глубине мира. Вероятность их получения и количество зависят от глубины (от 1 на верху до 5 внизу)");
        rbMineralsAccHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMineralsAccHeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSettingsWorldLayout = new javax.swing.GroupLayout(panelSettingsWorld);
        panelSettingsWorld.setLayout(panelSettingsWorldLayout);
        panelSettingsWorldLayout.setHorizontalGroup(
            panelSettingsWorldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsWorldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSettingsWorldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(rbMineralsAccClassic)
                    .addComponent(rbMineralsAccHeight))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        panelSettingsWorldLayout.setVerticalGroup(
            panelSettingsWorldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsWorldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMineralsAccClassic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMineralsAccHeight)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Мир", panelSettingsWorld);

        cbMultiCell.setText("многоклеточность");
        cbMultiCell.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbMultiCellStateChanged(evt);
            }
        });

        cbRelativeByEnergy.setText("похожие по энергии (experimental)");
        cbRelativeByEnergy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                energyRelativeChanged(evt);
            }
        });

        cbRelativeByMinerals.setText("похожие по минералам (experimental)");
        cbRelativeByMinerals.setToolTipText("Боты будут отличать соседей, у которых количество минералов примерно такое-же");
        cbRelativeByMinerals.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mineralsRelativeChanged(evt);
            }
        });

        javax.swing.GroupLayout panelSettingaBotsLayout = new javax.swing.GroupLayout(panelSettingaBots);
        panelSettingaBots.setLayout(panelSettingaBotsLayout);
        panelSettingaBotsLayout.setHorizontalGroup(
            panelSettingaBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingaBotsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSettingaBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMultiCell)
                    .addComponent(cbRelativeByEnergy)
                    .addComponent(cbRelativeByMinerals))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelSettingaBotsLayout.setVerticalGroup(
            panelSettingaBotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingaBotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbMultiCell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRelativeByMinerals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRelativeByEnergy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Боты", panelSettingaBots);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonOk.setText("ОК");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonOk);

        buttonCancel.setText("Отмена");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonCancel);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
        getContentPane().add(filler1, java.awt.BorderLayout.NORTH);
        getContentPane().add(filler2, java.awt.BorderLayout.WEST);
        getContentPane().add(filler3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        saveAndClose();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void cbMultiCellStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbMultiCellStateChanged
        JCheckBox cb = (JCheckBox) evt.getSource();
        changedSettings.put("EnableMultiCell", cb.isSelected() ? "true" : "false");
    }//GEN-LAST:event_cbMultiCellStateChanged

    private void rbMineralsAccClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMineralsAccClassicActionPerformed
        changedSettings.put("MineralsAccumulation", "classic");
    }//GEN-LAST:event_rbMineralsAccClassicActionPerformed

    private void rbMineralsAccHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMineralsAccHeightActionPerformed
        changedSettings.put("MineralsAccumulation", "height");
    }//GEN-LAST:event_rbMineralsAccHeightActionPerformed

    private void mineralsRelativeChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mineralsRelativeChanged
        JCheckBox cb = (JCheckBox) evt.getSource();
        changedSettings.put("EnableRelativeByMinerals", cb.isSelected() ? "true" : "false");
    }//GEN-LAST:event_mineralsRelativeChanged

    private void energyRelativeChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_energyRelativeChanged
        JCheckBox cb = (JCheckBox) evt.getSource();
        changedSettings.put("EnableRelativeByEnergy", cb.isSelected() ? "true" : "false");
    }//GEN-LAST:event_energyRelativeChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMineralsAccumulation;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox cbMultiCell;
    private javax.swing.JCheckBox cbRelativeByEnergy;
    private javax.swing.JCheckBox cbRelativeByMinerals;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDevNote;
    private javax.swing.JPanel panelSettingaBots;
    private javax.swing.JPanel panelSettingsGeneral;
    private javax.swing.JPanel panelSettingsWorld;
    private javax.swing.JRadioButton rbMineralsAccClassic;
    private javax.swing.JRadioButton rbMineralsAccHeight;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    //CHECKSTYLE:ON

    /**
     * Отобразить диалог параметров.
     */
    public void showSettingsDialog() {
        setLocationRelativeTo(getParent());
        setVisible(true);
    }

    private void saveAndClose() {
        Set<Map.Entry<String, String>> changedSet = changedSettings.entrySet();
        for (Map.Entry<String, String> entry: changedSet) {
            properties.setProperty(entry.getKey(), entry.getValue());
        }
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

}
